[server]
fileWatcherType = "poll"
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50

[theme]
base = "light"
primaryColor = "#176B50"
backgroundColor = "#F3F1EB"
secondaryBackgroundColor = "#FFFEFB"
textColor = "#17211D"
font = "sans serif"

[browser]
gatherUsageStats = false
