[server]
fileWatcherType = "none"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[theme]
base = "light"
primaryColor = "#195846"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8F5"
textColor = "#202D29"
font = "sans serif"

[browser]
gatherUsageStats = false
